id: /subscriptions/81b40ada-2c53-4c7b-911c-8ceaeeae3046/resourceGroups/RG-Anniversary-EastUS/providers/Microsoft.App/containerapps/anniversary-app
identity:
  type: None
location: East US
name: anniversary-app
properties:
  configuration:
    activeRevisionsMode: Single
    dapr: null
    identitySettings: []
    ingress:
      additionalPortMappings: null
      allowInsecure: false
      clientCertificateMode: null
      corsPolicy: null
      customDomains: null
      exposedPort: 0
      external: true
      fqdn: anniversary-app.happyocean-b61820e5.eastus.azurecontainerapps.io
      ipSecurityRestrictions: null
      stickySessions: null
      targetPort: 80
      targetPortHttpScheme: null
      traffic:
      - latestRevision: true
        weight: 100
      transport: Auto
    maxInactiveRevisions: 100
    registries:
    - identity: ''
      passwordSecretRef: anniversaryregazurecrio-anniversaryreg
      server: anniversaryreg.azurecr.io
      username: anniversaryreg
    revisionTransitionThreshold: null
    runtime: null
    secrets:
    - name: anniversaryregazurecrio-anniversaryreg
    service: null
    targetLabel: ''
  customDomainVerificationId: F233186ED1D255970F0ADB79708C4BBF8DA9860882636738F9BF9D8C35C64941
  delegatedIdentities: []
  environmentId: /subscriptions/81b40ada-2c53-4c7b-911c-8ceaeeae3046/resourceGroups/vote-app-rg/providers/Microsoft.App/managedEnvironments/vote-app-env
  eventStreamEndpoint: https://eastus.azurecontainerapps.dev/subscriptions/81b40ada-2c53-4c7b-911c-8ceaeeae3046/resourceGroups/RG-Anniversary-EastUS/containerApps/anniversary-app/eventstream
  latestReadyRevisionName: anniversary-app--0000002
  latestRevisionFqdn: anniversary-app--0000002.happyocean-b61820e5.eastus.azurecontainerapps.io
  latestRevisionName: anniversary-app--0000002
  managedEnvironmentId: /subscriptions/81b40ada-2c53-4c7b-911c-8ceaeeae3046/resourceGroups/vote-app-rg/providers/Microsoft.App/managedEnvironments/vote-app-env
  outboundIpAddresses:
  - 20.231.246.122
  - 20.231.246.54
  - 40.121.19.105
  - 40.121.18.246
  - 40.121.18.166
  - 40.121.18.60
  - 40.121.18.21
  - 40.121.18.44
  - 40.121.18.41
  - 40.121.18.248
  - 40.121.18.82
  - 40.121.19.108
  - 20.231.247.19
  - 40.121.19.125
  - 40.121.18.46
  - 40.117.125.130
  - 40.121.18.52
  - 40.121.18.33
  - 40.121.18.238
  - 40.121.19.2
  - 40.121.19.122
  - 40.121.19.19
  - 40.121.18.114
  - 20.231.246.253
  - 40.121.18.255
  - 40.121.18.164
  - 40.117.121.106
  - 40.121.18.27
  - 40.121.18.156
  - 40.121.18.117
  - 40.121.18.197
  - 40.121.18.133
  - 40.121.18.112
  - 40.121.18.106
  - 20.241.227.6
  - 40.121.19.89
  - 40.121.19.83
  - 40.121.18.131
  - 40.121.18.201
  - 40.121.18.170
  - 40.121.18.242
  - 13.92.130.42
  - 40.121.19.42
  - 40.121.18.73
  - 40.121.18.43
  - 20.241.226.169
  - 51.8.12.17
  - 4.156.180.142
  - 20.242.162.124
  - 40.121.19.74
  - 40.121.19.40
  - 40.121.18.62
  - 40.121.18.244
  - 20.127.248.50
  - 20.241.171.30
  - 20.169.229.88
  - 20.169.229.46
  - 20.169.229.29
  - 20.169.229.38
  - 20.169.229.62
  - 20.169.229.109
  - 20.169.229.92
  - 20.169.229.27
  - 20.169.229.51
  - 20.169.229.42
  - 20.241.172.248
  - 48.216.192.198
  - 40.90.243.232
  - 40.90.242.126
  - 135.237.112.47
  - 51.8.74.190
  - 4.157.197.142
  - 172.210.91.191
  - 172.210.90.42
  - 40.90.243.227
  - 40.90.243.72
  - 20.241.172.250
  - 52.234.235.220
  - 57.152.55.92
  - 172.212.36.156
  - 172.210.121.45
  - 172.214.2.208
  - 51.8.15.68
  - 172.210.90.119
  - 134.33.213.81
  - 128.203.83.220
  - 20.241.192.93
  - 20.246.203.138
  - 172.212.121.150
  - 172.171.186.158
  - 52.249.213.152
  - 74.179.213.114
  - 4.246.239.152
  - 4.156.216.65
  - 4.157.231.174
  - 172.171.168.136
  - 20.185.213.14
  - 20.246.203.140
  - 13.82.216.169
  - 13.82.216.172
  - 13.82.216.149
  - 52.170.33.171
  - 20.242.208.88
  patchingMode: Automatic
  provisioningState: Succeeded
  runningStatus: Running
  template:
    containers:
    - image: anniversaryreg.azurecr.io/anniversary-dinner:6a09a3dba540c0bc82e7fa67c2087210f3566640
      imageType: ContainerImage
      name: anniversary-app
      resources:
        cpu: 0.5
        ephemeralStorage: 2Gi
        memory: 1Gi
    initContainers: null
    revisionSuffix: ''
    scale:
      cooldownPeriod: 300
      maxReplicas: 10
      minReplicas: null
      pollingInterval: 30
      rules: null
    serviceBinds: null
    terminationGracePeriodSeconds: null
    volumes: null
  workloadProfileName: Consumption
resourceGroup: RG-Anniversary-EastUS
systemData:
  createdAt: '2025-12-05T16:35:27.3458871'
  createdBy: me.dolores.celestina@gmail.com
  createdByType: User
  lastModifiedAt: '2025-12-05T16:51:07.5277679'
  lastModifiedBy: b42b6c88-becd-479f-b3a7-280c784c8f6d
  lastModifiedByType: Application
type: Microsoft.App/containerApps
